services:
  mysql:
    image: mysql:8.4.9-oraclelinux9
    restart: unless-stopped
    env_file:
      - "secrets.enc.env"
      - ".env"
    volumes:
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/mysql-data:/var/lib/mysql'
    networks:
      default:

  app:
    build: .
    depends_on:
    - mysql
    restart: unless-stopped
    env_file:
      - "secrets.enc.env"
      - ".env"
    volumes:
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/uploads:/var/www/bookstack/public/uploads'
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/storage-uploads:/var/www/bookstack/storage/uploads'
#    ports:
#    - "8080:8080"
    networks:
      default:
      system_internal:

networks:
  default:
  system_internal:
    external: true
